---
- hosts: test
  become: true
  vars:
      user_name: user1
      test_user_password: pusheen

  tasks:
  - name: Create user
    user:
      password: "{{ test_user_password | password_hash('sha512') }}"
      name: {{ user_name }}
      generate_ssh_key: true

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: {{ user_name }}
      state: present
      key: "{{ lookup('file', './id_rsa.pub') }}"
