---
- name: create users with sudo rights
  hosts: test
  become: yes
  vars:
      group_name: superusers

  tasks:
  - name: create group
    group:
      name: "{{ group_name }}"

  - name: create and add users to group
    user:
      name: "{{ item.name }}"
      group: "{{ group_name }}"
      password: "{{ item.password | password_hash('sha512') }}"
    loop:
      - { name: 'user2', password: 'pumpumpum' }
      - { name: 'user3', password: 'piupiupiu' }


  - name: add sudo group
    lineinfile:
      path: /etc/sudoers
      state: present
      line: '%superusers ALL=(ALL) ALL'
      validate: /usr/sbin/visudo -cf %s

