---
- name: install docker
  hosts: localhost

  tasks:
  - name: install a few prerequisite packages which let apt use packages over HTTPS
    apt:
      name: apt-transport-https,ca-certificates,curl,software-properties-common
      state: latest
      update_cache: yes
  - name: add the GPG key for the official Docker repository to the system
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add the Docker repository to APT sources
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
  - name: installing and starting the daemon Docker
    apt:
      name: docker-ce
  - name: Start docker
    service:
      name: docker
      state: started
      enabled: yes
